### ISSUE TITLE
Cannot run the project

### ISSUE THREAD

**Issue by tird** [ChiefOfGxBxL/Ice-Sickle#32]
Tried to run src code and I got this:
npm start
![default](https://user-images.githubusercontent.com/13370118/33799938-bc21f978-dd3e-11e7-8f9e-8a45c6da739b.png)

**Comment by ChiefOfGxBxL** [comment]
Hi, thanks for reporting this issue.

I'll work on a fix this week. I know what's causing this issue. `settings.json` file is missing, because I don't have the program set up to create it if it does not exist. Since the project is under a lot of development I just hand-write that file, but I'll work on having it generated if missing!

**Comment by ChiefOfGxBxL** [comment]
All fixed!

Sorry for the delay. Lots of stuff was going on for the holidays, so I wasn't able to get to it until now.
